// ============ Product Catalog ============
const PRODUCTS = [
  { id:"akasha-PDF", name:"Akasha Chronik - PDF Antwort", category:"Akasha", price:49, duration:0, format:["PDF"], image:"images/akasha pdf.png", short:"Akasha Reading - zu Deinem beliebigen Thema oder Blockade", description:"Vielen Dank für dein Vertrauen. ♥<br> <br>Ich verbinde mich mit deiner persönlichen Akasha Chronik und schaue mir Dein individuelles Thema oder Blockade an.<br>Ich sende dir innerhalb der nächsten 7 Tage ein ausführliches PDF oder allenfalls Sprachmemo.<br><br>- Ursprung Blockade (dieses Leben oder allenfalls früheres Leben) <br>- Thema und Glaubenssätze dahinter<br>- Impulse und Tipps von mir und aus deiner Akasha zum lösen der Blockade<br><br>Wenn kein bestimmtes Thema von dir aus kommt, mache ich in der Akasha eine \"Standortbestimmung\" und schaue was für Impulse/Thema aufkommen.<br><br>Ich freue mich dir als ausgebildetes Medium weiterhelfen zu können. ♡ <br><br> Ich kontaktiere dich schnellstmöglich nach der Buchung, damit du mir dein Thema mitteilen kannst.", rating:4.9, reviews:284, },
  { id:"akasha-reading", name:"Akasha Chronik-Reading", category:"Akasha", price:79, duration:60, format:["Online","Telefon"], image:"images/akasha.jpg", short:"Akasha Reading - zu Deinem beliebigen Thema oder Blockade", description:"Vielen Dank für dein Vertrauen. ♥<br> <br>Ich verbinde mich mit deiner persönlichen Akasha Chronik und wir schauen uns Dein individuelles Thema oder Blockade an.<br><br>- Ursprung Blockade (dieses Leben oder allenfalls früheres Leben) <br>- Thema und Glaubenssätze dahinter<br>- Impulse und Tipps von mir und aus deiner Akasha zum lösen der Blockade<br><br>Wenn kein bestimmtes Thema von dir aus kommt, mache ich in der Akasha eine \"Standortbestimmung\" und schaue was für Impulse/Thema aufkommen.<br><br>Ich freue mich dir als ausgebildetes Medium weiterhelfen zu können. ♡ <br><br> Ich kontaktiere dich schnellstmöglich nach der Buchung und wir finden gemeinsam einen passenden Termin, für ca. 1h, innerhalb der nächsten 7 Tage.<br>Der Call/Videocall kann per Telefon, Whatsapp, Zoom oder Sonstiges ausgehen, das ist ganz dir überlassen.", rating:4.9, reviews:284, bestseller:true },
  { id:"tarot-klassik", name:"Klassisches Tarot-Reading", category:"Tarot", price:59, duration:30, format:["Online","Telefon"], image:"images/sm-tarot.jpg", short:"Legung nach Rider-Waite für klare Antworten.", description:"Eine tiefgehende 7-Karten-Legung, die Licht in deine aktuelle Situation bringt – Liebe, Beruf oder Lebensweg.", rating:4.9, reviews:284, bestseller:true },
  { id:"tarot-liebe", name:"Liebes-Tarot", category:"Tarot", price:79, duration:45, format:["Online","Telefon","Chat"], image:"images/sm-tarot.jpg", short:"Herzensfragen & Beziehungsklarheit.", description:"Spezialisiertes Reading für alle Herzensangelegenheiten. Erkenne Muster, Blockaden und den Weg zu wahrer Verbindung.", rating:4.8, reviews:512, new:true },
  { id:"kristall-blick", name:"Kristallkugel-Blick", category:"Kristallkugel", price:89, duration:40, format:["Online"], image:"images/sm-crystal.jpg", short:"Intuitives Schauen in die nahe Zukunft.", description:"Ein traditionelles Scrying-Reading. Erhalte Bilder, Symbole und Botschaften für die nächsten 3–6 Monate.", rating:4.7, reviews:156},
  { id:"aura-reading", name:"Aura & Chakra Reading", category:"Aura", price:99, duration:60, format:["Online"], image:"images/sm-aura.jpg", short:"Energiefeld-Analyse mit Empfehlungen.", description:"Ich lese dein Energiefeld und erkenne Blockaden in den 7 Chakren – inklusive individueller Reinigungs-Ritualempfehlungen.", rating:5.0, reviews:98, bestseller:true },
  { id:"natal-chart", name:"Geburtshoroskop-Deutung", category:"Astrologie", price:129, duration:75, format:["Online","Telefon"], image:"images/sm-astro.jpg", short:"Komplette Natal-Chart-Analyse.", description:"Entdecke deinen Seelenplan: Sonne, Mond, Aszendent, Häuser & Aspekte – inkl. PDF-Chart zum Mitnehmen.", rating:4.9, reviews:347, bestseller:true },
  { id:"transit-jahr", name:"Jahres-Transit Reading", category:"Astrologie", price:149, duration:90, format:["Online"], image:"images/sm-astro.jpg", short:"Dein persönliches Jahr voraus.", description:"Was bringt dir das kommende Jahr? Analyse aller wichtigen Transite mit Monats-Highlights.", rating:4.8, reviews:201 },
  { id:"pendel-ja-nein", name:"Pendel-Reading Kompakt", category:"Pendel", price:29, duration:15, format:["Chat","Telefon"], image:"images/sm-pendel.jpg", short:"Schnelle Ja/Nein-Klarheit.", description:"Bis zu 5 konkrete Ja/Nein-Fragen mit dem Pendel beantwortet – ideal für schnelle Entscheidungen.", rating:4.6, reviews:432 },
  { id:"channeling", name:"Channeling-Session", category:"Channeling", price:159, duration:60, format:["Online"], image:"images/sm-channel.jpg", short:"Botschaften deiner Geistführer.", description:"Ich verbinde mich mit deinen Geistführern und Ahnen und übermittle persönliche Botschaften für deinen Weg.", rating:4.9, reviews:178, new:true },
  { id:"runen-wurf", name:"Runen-Reading", category:"Runen", price:69, duration:30, format:["Online","Chat"], image:"images/sm-runen.jpg", short:"Nordische Weisheit für deinen Weg.", description:"Die 9-Runen-Legung der nordischen Tradition – kraftvoll für Lebensentscheidungen und Schicksalsfragen.", rating:4.7, reviews:134 },
  { id:"mini-tarot", name:"Tagesbotschaft", category:"Tarot", price:19, duration:10, format:["Chat"], image:"images/sm-tarot.jpg", short:"Eine Karte, eine Antwort.", description:"Deine persönliche Tageskarte mit ausführlicher Deutung per Chat – der perfekte spirituelle Start in den Tag.", rating:4.8, reviews:890 },
  { id:"aura-foto", name:"Aura-Farb-Deutung", category:"Aura", price:49, duration:25, format:["Online"], image:"images/sm-aura.jpg", short:"Deine Aura-Farbe enthüllt.", description:"Finde heraus, welche Farbe deine Aura aktuell dominiert und was das über deinen Seelenzustand verrät.", rating:4.5, reviews:76 },
  { id:"partnerhoroskop", name:"Partner-Synastrie", category:"Astrologie", price:179, duration:90, format:["Online"], image:"images/sm-astro.jpg", short:"Eure kosmische Kompatibilität.", description:"Vergleich zweier Geburtshoroskope: Seelenverwandtschaft, Konflikte & Potenziale eurer Beziehung.", rating:4.9, reviews:223 },
];

const CATEGORIES = ["Tarot","Astrologie","Aura","Channeling","Pendel","Runen","Kristallkugel","Akasha"];
const FORMATS = ["Online","Telefon","Chat","PDF"];

const REVIEWS = [
  { name:"Sarah M.", reading:"Liebes-Tarot", stars:5, text:"Luna hat Dinge gesehen, die ich niemandem erzählt hatte. Absolut treffsicher und unglaublich einfühlsam. Ich gehe mit so viel mehr Klarheit aus dieser Session." },
  { name:"Michael K.", reading:"Geburtshoroskop", stars:5, text:"Das beste Astrologie-Reading, das ich je hatte. Sehr professionell, fundiert und gleichzeitig herzlich. Das PDF nutze ich jetzt regelmässig als Wegweiser." },
  { name:"Jana B.", reading:"Aura & Chakra Reading", stars:5, text:"Ich war skeptisch – jetzt bin ich Stammkundin. Die Energie-Analyse war auf den Punkt, und die Ritualempfehlungen wirken wirklich." },
  { name:"Tobias R.", reading:"Channeling-Session", stars:5, text:"Eine zutiefst berührende Erfahrung. Ich habe Antworten von meiner verstorbenen Grossmutter erhalten, die nur sie wissen konnte. Tränen, aber heilende." },
  { name:"Léa F.", reading:"Klassisches Tarot", stars:4, text:"Sehr schöne Atmosphäre, klare Aussagen und gute Fragestellungen. Beim nächsten Mal buche ich gleich das längere Reading." },
  { name:"Andrea P.", reading:"Pendel-Reading", stars:5, text:"Schnell, präzise und genau das, was ich brauchte für eine wichtige berufliche Entscheidung. Hat mir wirklich geholfen." },
];
