// ============ Product Catalog ============
const PRODUCTS = [
  { id:"akasha-PDF", name:"Akasha Chronik - PDF Antwort", category:"Akasha", price:49, duration:0, format:["PDF"], image:"images/akasha pdf.png", short:"Akasha Reading - zu Deinem beliebigen Thema oder Blockade", description:"Vielen Dank für dein Vertrauen. ♥<br> <br>Ich verbinde mich mit deiner persönlichen Akasha Chronik und schaue mir Dein individuelles Thema oder Blockade an.<br>Ich sende dir innerhalb der nächsten 7 Tage ein ausführliches PDF oder allenfalls Sprachmemo.<br><br>- Ursprung Blockade (dieses Leben oder allenfalls früheres Leben) <br>- Thema und Glaubenssätze dahinter<br>- Impulse und Tipps von mir und aus deiner Akasha zum lösen der Blockade<br><br>Wenn kein bestimmtes Thema von dir aus kommt, mache ich in der Akasha eine \"Standortbestimmung\" und schaue was für Impulse/Thema aufkommen.<br><br>Ich freue mich dir als ausgebildetes Medium weiterhelfen zu können. ♡ <br><br> Ich kontaktiere dich schnellstmöglich nach der Buchung, damit du mir dein Thema mitteilen kannst.", rating:4.9, reviews:284, },
  { id:"akasha-reading", name:"Akasha Chronik-Reading", category:"Akasha", price:79, duration:60, format:["Online","Telefon"], image:"images/akasha.jpg", short:"Akasha Reading - zu Deinem beliebigen Thema oder Blockade", description:"Vielen Dank für dein Vertrauen. ♥<br> <br>Ich verbinde mich mit deiner persönlichen Akasha Chronik und wir schauen uns Dein individuelles Thema oder Blockade an.<br><br>- Ursprung Blockade (dieses Leben oder allenfalls früheres Leben) <br>- Thema und Glaubenssätze dahinter<br>- Impulse und Tipps von mir und aus deiner Akasha zum lösen der Blockade<br><br>Wenn kein bestimmtes Thema von dir aus kommt, mache ich in der Akasha eine \"Standortbestimmung\" und schaue was für Impulse/Thema aufkommen.<br><br>Ich freue mich dir als ausgebildetes Medium weiterhelfen zu können. ♡ <br><br> Ich kontaktiere dich schnellstmöglich nach der Buchung und wir finden gemeinsam einen passenden Termin, für ca. 1h, innerhalb der nächsten 7 Tage.<br>Der Call/Videocall kann per Telefon, Whatsapp, Zoom oder Sonstiges ausgehen, das ist ganz dir überlassen.", rating:4.9, reviews:284, bestseller:true },
  { id:"chakra-reading", name:"Chakra-Reading", category:"Chakra", price:59, duration:30, format:["Online","Telefon"], image:"images/chakra.png", short:"Chakra analysen mit Empfehlungen.", description:"Eine tiefgehende Chakra analyse, die Licht in deine aktuelle Situation bringt – Blockaden, Beschwerden oder Lebensweg.", rating:4.9, reviews:284, bestseller:true },
  { id:"energiearbeit", name:"Energiearbeit", category:"Energiearbeit", price:79, duration:45, format:["Online","Telefon","Chat"], image:"images/chakra.png", short:"Energetische Blockaden lösen.", description:"Energetische Blockadenlösung von Blockaden, alten Glaubensmustern und tipps zur Energieanhebung.", rating:4.8, reviews:512, new:true },
  { id:"aura-reading", name:"Aura & Chakra Reading", category:"Aura", price:99, duration:60, format:["Online"], image:"images/sm-aura.jpg", short:"Energiefeld-Analyse mit Empfehlungen.", description:"Ich lese dein Energiefeld und erkenne Blockaden in den 7 Chakren – inklusive individueller Reinigungs-Ritualempfehlungen.", rating:5.0, reviews:98, bestseller:true },
  { id:"natal-chart", name:"Geburtshoroskop-Deutung", category:"Astrologie", price:129, duration:75, format:["Online","Telefon"], image:"images/sm-astro.jpg", short:"Komplette Natal-Chart-Analyse.", description:"Entdecke deinen Seelenplan: Sonne, Mond, Aszendent, Häuser & Aspekte – inkl. PDF-Chart zum Mitnehmen.", rating:4.9, reviews:347, bestseller:true },
  { id:"transit-jahr", name:"Jahres-Transit Reading", category:"Astrologie", price:149, duration:90, format:["Online"], image:"images/sm-astro.jpg", short:"Dein persönliches Jahr voraus.", description:"Was bringt dir das kommende Jahr? Analyse aller wichtigen Transite mit Monats-Highlights.", rating:4.8, reviews:201 },
  { id:"channeling", name:"Channeling-Session", category:"Channeling", price:159, duration:60, format:["Online"], image:"images/sm-channel.jpg", short:"Botschaften deiner Seelenführung.", description:"Ich verbinde mich mit deiner Seelenführung und deinen Ahnen und übermittle persönliche Botschaften für deinen Weg.", rating:4.9, reviews:178, new:true },
  { id:"channeling", name:"Tagesbotschaft", category:"Channeling", price:19, duration:10, format:["Chat"], image:"images/sm-channel.jpg", short:"Impuls der geistigen Welt zu deiner Frage.", description:"Ich verbinde mich mit der geistigen Welt und gebe dir eine Antwort und Impulse zu deiner persönlichen Frage.", rating:4.8, reviews:890 },
  { id:"aura-foto", name:"Aura-Farb-Deutung", category:"Aura", price:49, duration:25, format:["Online"], image:"images/sm-aura.jpg", short:"Deine Aura-Farbe enthüllt.", description:"Finde heraus, welche Farbe deine Aura aktuell dominiert und was das über deinen Seelenzustand verrät.", rating:4.5, reviews:76 },
  { id:"partnerhoroskop", name:"Partner-Synastrie", category:"Astrologie", price:179, duration:90, format:["Online"], image:"images/sm-astro.jpg", short:"Eure kosmische Kompatibilität.", description:"Vergleich zweier Geburtshoroskope: Seelenverwandtschaft, Konflikte & Potenziale eurer Beziehung.", rating:4.9, reviews:223 },
];

const CATEGORIES = ["Astrologie","Aura","Channeling","Chakra", "Akasha", "Energiearbeit"];
const FORMATS = ["Online","Telefon","Chat","PDF"];

const REVIEWS = [
  { name:"Sarah M.", reading:"Akasha-Reading", stars:5, text:"Luna hat Dinge gewusst, die ich niemandem erzählt hatte. Absolut treffsicher und unglaublich einfühlsam. Ich gehe mit so viel mehr Klarheit aus dieser Session." },
  { name:"Michael K.", reading:"Geburtshoroskop", stars:5, text:"Das beste Astrologie-Reading, das ich je hatte. Sehr professionell, fundiert und gleichzeitig herzlich. Das PDF nutze ich jetzt regelmässig als Wegweiser." },
  { name:"Jana B.", reading:"Aura & Chakra Reading", stars:5, text:"Ich war skeptisch – jetzt bin ich Stammkundin. Die Energie-Analyse war auf den Punkt, und die Ritualempfehlungen wirken wirklich." },
  { name:"Tobias R.", reading:"Channeling-Session", stars:5, text:"Eine zutiefst berührende Erfahrung. Ich habe Antworten von meinem Higher Self erhalöten, die mir sehr weitergeholfen haben, meinen eigenen Weg weiter zu gehen." },
  { name:"Léa F.", reading:"Akasha-Reading", stars:4, text:"Sehr schöne Atmosphäre, klare Aussagen und gute Fragestellungen. Beim nächsten Mal buche ich gleich das längere Reading." },
  { name:"Andrea P.", reading:"Channeling-Session", stars:5, text:"Schnell, präzise und genau das, was ich brauchte für eine wichtige berufliche Entscheidung. Hat mir wirklich geholfen." },
];
